### PR TITLE
update widdershins/shins

### PR DESCRIPTION
**Pull request by lagebaue**
- updates widdershins/shins to newest version
- also adds implicit dependencies (js-yaml was no longer available, added chalk just for completeness)

### CODE REVIEW

**Comment by tobilg** [comment]
Hi @lagebaue, thanks a lot for the PR. As widdershins had a major version update, did you also test whether there are any side effects?

**Comment by lagebaue** [comment]
Sorry, it does not work. Was in a hurry yesterday and just quickly ran it. The CLI output looked fine, but didn't properly create the html. I still had an existing html from the previous runs in the output folder... 

Consider this PR WIP for now.

**Comment by lagebaue** [comment]
Tested with a 2000+ lines spec file. Output is as expected (no structural differences, mostly only changes in the code snippets, template)

**Comment by tobilg** [comment]
Thanks @lagebaue! I'll test it over the weekend, as I'm currently a bit short on free time unfortunately

**Comment by tobilg** [comment]
@lagebaue I just released version `0.4.0`. Thanks again.

**Pull request merged**
